import { Button, Card, CardContent, Grid, Slider } from "@mui/material";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Water Quality ML Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg-blue-400 mx-10">
          <h1 className="font-bold text-2xl text-center my-4">Water Quality</h1>
        </div>
        <Card>
          <CardContent>
            <form className="bg-blue-50 px-10 py-10">
              <Grid container spacing={5}>
                <Grid
                  xs={12}
                  sm={5}
                  item
                  className="bg-blue-100 rounded-lg m-3 px-3"
                >
                  <h2>PH</h2>
                  <Slider
                    defaultValue={0}
                    aria-label="Default"
                    valueLabelDisplay="auto"
                    required
                  />
                </Grid>
                <Grid
                  xs={12}
                  sm={5}
                  item
                  className="bg-blue-100 rounded-lg m-3 px-3"
                >
                  <h2>Hardness</h2>
                  <Slider
                    defaultValue={0}
                    aria-label="Default"
                    valueLabelDisplay="auto"
                    required
                  />
                </Grid>
                <Grid
                  xs={12}
                  sm={5}
                  item
                  className="bg-blue-100 rounded-lg m-3 px-3"
                >
                  <h2>Solids</h2>
                  <Slider
                    defaultValue={0}
                    aria-label="Default"
                    valueLabelDisplay="auto"
                    required
                  />
                </Grid>
                <Grid
                  xs={12}
                  sm={5}
                  item
                  className="bg-blue-100 rounded-lg m-3 px-3"
                >
                  <h2>Chloramines</h2>
                  <Slider
                    defaultValue={0}
                    aria-label="Default"
                    valueLabelDisplay="auto"
                    required
                  />
                </Grid>
                <Grid
                  xs={12}
                  sm={5}
                  item
                  className="bg-blue-100 rounded-lg m-3 px-3"
                >
                  <h2>Sulfate</h2>
                  <Slider
                    defaultValue={0}
                    aria-label="Default"
                    valueLabelDisplay="auto"
                    required
                  />
                </Grid>
                <Grid
                  xs={12}
                  sm={5}
                  item
                  className="bg-blue-100 rounded-lg m-3 px-3"
                >
                  <h2>Conductivity</h2>
                  <Slider
                    defaultValue={0}
                    aria-label="Default"
                    valueLabelDisplay="auto"
                    required
                  />
                </Grid>
                <Grid
                  xs={12}
                  sm={5}
                  item
                  className="bg-blue-100 rounded-lg m-3 px-3"
                >
                  <h2>Turbidity</h2>
                  <Slider
                    defaultValue={0}
                    aria-label="Default"
                    valueLabelDisplay="auto"
                    required
                  />
                </Grid>
                <Grid
                  xs={12}
                  sm={5}
                  item
                  className="bg-blue-100 rounded-lg m-3 px-3"
                >
                  <h2>Trihalomethanes</h2>
                  <Slider
                    defaultValue={0}
                    aria-label="Default"
                    valueLabelDisplay="auto"
                    required
                  />
                </Grid>
                <Grid
                  xs={12}
                  sm={5}
                  item
                  className="bg-blue-100 rounded-lg m-3 px-3"
                >
                  <h2>Organic_carbon</h2>
                  <Slider
                    defaultValue={0}
                    aria-label="Default"
                    valueLabelDisplay="auto"
                    required
                  />
                </Grid>

                <Grid xs={12} item>
                  <Button
                    type="submit"
                    variant="contained"
                    color="primary"
                    fullWidth
                  >
                    Check Result
                  </Button>
                </Grid>
              </Grid>
            </form>
            <div>
              <h2>Nice Result</h2>
            </div>
            <div>
              <h2>Bad Result</h2>
            </div>
          </CardContent>
        </Card>
      </main>
    </div>
  );
}
